name: Feature Request
description: Suggest an idea for Leaflet.markercluster
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I've searched through existing issues to make sure this isn't a duplicate
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you'd like
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Describe the problem this feature would solve
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, mockups, or examples
